# Required metadata
sonar.projectKey=evershop
sonar.projectName=evershop
sonar.projectVersion=1.0

# Path to source code
sonar.sources=src

# Language settings
sonar.language=js

# SonarQube Server
sonar.host.url=http://localhost:9000

# Authentication token (the one you generated)
sonar.login=sqp_e4b83fd98793dc8a9f405aeb35953674af66e8b7
